# Generated by Django 5.0.6 on 2024-06-09 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.PositiveBigIntegerField()),
                ('brand', models.CharField(choices=[('CE', 'CE'), ('EXTC', 'EXTC'), ('ME', 'ME'), ('AI', 'AI'), ('IT', 'IT')], max_length=30)),
            ],
        ),
    ]
